/* TR81 — paylaşılan 40-dil i18n. Tüm sayfalar bu dosyayı YÜKLER, sonra window.I18N.t / .lang kullanır.
   Cihaz dili 40 dilden biriyse o dil, değilse İngilizce. Türkçe açıkça 'tr'.
   Eksik anahtarlar İngilizce'ye (D.en) düşer — bu yüzden ikincil dillerde sadece çekirdek anahtarlar var. */
window.I18N=(function(){
const REG={
  en:{medit:'Mediterranean',marmara:'Marmara',aegean:'Aegean',black:'Black Sea',central:'Central Anatolia',east:'Eastern Anatolia',southeast:'Southeastern Anatolia'},
  tr:{medit:'Akdeniz',marmara:'Marmara',aegean:'Ege',black:'Karadeniz',central:'İç Anadolu',east:'Doğu Anadolu',southeast:'Güneydoğu Anadolu'}
};
const D={
en:{h1:'Discover<br>Türkiye',tag:'Scenic locations across 81 provinces.',scroll:'Scroll ↓',trend:'Trending',trendsub:'The most-visited places.',regions:'Regions',search:'Search a province…',swipe:'Swipe',
  tap:'Open',freeTap:'Free',lockedTap:'Buy',unlockBtn:'Buy',ownTxt:'Owned',explore:'Explore',pwBuy:'Unlock all 81',pwTry:'Explore Muğla now',pwLocked:'locked',
  haveCode:'I have a code',codePh:'Enter your code',codeGo:'Unlock',codeOk:'Unlocked! Redirecting…',codeErr:'That code is not valid.',codeEmpty:'Enter your code.',
  maps:'Directions',spots:'scenic spots to explore',fullH:'Next stop: the world',fullP:'You’ve explored Türkiye. Now every location in the world awaits.',fullB:'All World Locations',
  demoH:'So many places to explore',demoP:'Every one of the 81 provinces has special spots waiting. Unlock them all.',demoB:'All 81',empty:'Loading…',fail:'Could not load locations.'},
tr:{h1:'Türkiye<span class="sfx">’yi</span><br>Keşfet',tag:'81 ilin manzaralı konumları.',scroll:'Kaydır ↓',trend:'Popüler',trendsub:'En çok ziyaret edilen yerler.',regions:'Bölgeler',search:'İl ara…',swipe:'Kaydır',
  tap:'Aç',freeTap:'Ücretsiz',lockedTap:'Satın al',unlockBtn:'Satın Al',ownTxt:'Açık',explore:'Keşfet',pwBuy:'81 İl Kilidini Aç',pwTry:'Muğla konumlarına şimdi eriş',pwLocked:'kilitli',
  haveCode:'Kodum var',codePh:'Kodunu gir',codeGo:'Aç',codeOk:'Açıldı! Yönlendiriliyorsunuz…',codeErr:'Bu kod geçersiz.',codeEmpty:'Lütfen kodunu gir.',
  maps:'Konum',spots:'manzaralı yerin konumları',fullH:'Sıradaki durak: dünya',fullP:'Türkiye’yi keşfettin. Şimdi tüm dünyanın konumları seni bekliyor.',fullB:'Tüm Dünya Konumları',
  demoH:'Gezilecek o kadar çok yer var ki',demoP:'81 ilin her birinde keşfedilmeyi bekleyen özel konumlar var. Hepsinin kilidini aç.',demoB:'81 İL',empty:'Yükleniyor…',fail:'Konumlar yüklenemedi.'},
de:{h1:'Entdecke<br>Türkiye',tag:'Sehenswerte Orte in 81 Provinzen.',trend:'Beliebt',regions:'Regionen',search:'Provinz suchen…',tap:'Öffnen',freeTap:'Gratis',lockedTap:'Kaufen',ownTxt:'Freigeschaltet',pwBuy:'Alle 81 freischalten',pwTry:'Muğla jetzt erkunden',pwLocked:'gesperrt',haveCode:'Ich habe einen Code',codePh:'Code eingeben',codeGo:'Freischalten',codeOk:'Freigeschaltet! Weiterleitung…',codeErr:'Dieser Code ist ungültig.',maps:'Route',spots:'sehenswerte Orte',fullH:'Nächstes Ziel: die Welt',fullP:'Du hast die Türkei erkundet. Jetzt wartet die ganze Welt.',fullB:'Alle Orte der Welt'},
fr:{h1:'Découvrez<br>Türkiye',tag:'Lieux panoramiques des 81 provinces.',trend:'Tendances',regions:'Régions',search:'Rechercher une province…',tap:'Ouvrir',freeTap:'Gratuit',lockedTap:'Acheter',ownTxt:'Débloqué',pwBuy:'Débloquer les 81',pwTry:'Explorer Muğla',pwLocked:'verrouillé',haveCode:'J’ai un code',codePh:'Entrez votre code',codeGo:'Débloquer',codeOk:'Débloqué ! Redirection…',codeErr:'Ce code n’est pas valide.',maps:'Itinéraire',spots:'lieux à découvrir',fullH:'Prochaine étape : le monde',fullP:'Vous avez exploré la Türkiye. Le monde entier vous attend.',fullB:'Tous les lieux du monde'},
es:{h1:'Descubre<br>Türkiye',tag:'Lugares panorámicos en 81 provincias.',trend:'Tendencias',regions:'Regiones',search:'Buscar provincia…',tap:'Abrir',freeTap:'Gratis',lockedTap:'Comprar',ownTxt:'Desbloqueado',pwBuy:'Desbloquear las 81',pwTry:'Explorar Muğla',pwLocked:'bloqueado',haveCode:'Tengo un código',codePh:'Introduce tu código',codeGo:'Desbloquear',codeOk:'¡Desbloqueado! Redirigiendo…',codeErr:'Este código no es válido.',maps:'Cómo llegar',spots:'lugares para explorar',fullH:'Siguiente parada: el mundo',fullP:'Has explorado Türkiye. Ahora te espera todo el mundo.',fullB:'Lugares del mundo'},
it:{h1:'Scopri<br>Türkiye',tag:'Luoghi panoramici in 81 province.',trend:'Di tendenza',regions:'Regioni',search:'Cerca una provincia…',tap:'Apri',freeTap:'Gratis',lockedTap:'Acquista',ownTxt:'Sbloccato',pwBuy:'Sblocca tutte le 81',pwTry:'Esplora Muğla',pwLocked:'bloccato',haveCode:'Ho un codice',codePh:'Inserisci il codice',codeGo:'Sblocca',codeOk:'Sbloccato! Reindirizzamento…',codeErr:'Codice non valido.',maps:'Indicazioni',spots:'luoghi da esplorare',fullH:'Prossima tappa: il mondo',fullP:'Hai esplorato la Türkiye. Ora ti aspetta il mondo intero.',fullB:'Luoghi nel mondo'},
pt:{h1:'Descubra<br>Türkiye',tag:'Lugares cênicos em 81 províncias.',trend:'Em alta',regions:'Regiões',search:'Buscar província…',tap:'Abrir',freeTap:'Grátis',lockedTap:'Comprar',ownTxt:'Desbloqueado',pwBuy:'Desbloquear as 81',pwTry:'Explorar Muğla',pwLocked:'bloqueado',haveCode:'Tenho um código',codePh:'Digite seu código',codeGo:'Desbloquear',codeOk:'Desbloqueado! Redirecionando…',codeErr:'Este código não é válido.',maps:'Como chegar',spots:'lugares para explorar',fullH:'Próxima parada: o mundo',fullP:'Você explorou a Türkiye. Agora o mundo inteiro espera.',fullB:'Lugares do mundo'},
ru:{h1:'Откройте<br>Türkiye',tag:'Живописные места в 81 провинции.',trend:'Популярное',regions:'Регионы',search:'Поиск провинции…',tap:'Открыть',freeTap:'Бесплатно',lockedTap:'Купить',ownTxt:'Открыто',pwBuy:'Открыть все 81',pwTry:'Открыть Мугла',pwLocked:'закрыто',haveCode:'У меня есть код',codePh:'Введите код',codeGo:'Открыть',codeOk:'Открыто! Перенаправление…',codeErr:'Код недействителен.',maps:'Маршрут',spots:'мест для изучения',fullH:'Следующая остановка: мир',fullP:'Вы изучили Türkiye. Теперь вас ждёт весь мир.',fullB:'Все места мира'},
ja:{h1:'見つけよう<br>Türkiye',tag:'81県の絶景スポット。',trend:'人気',regions:'地域',search:'県を検索…',tap:'開く',freeTap:'無料',lockedTap:'購入',ownTxt:'解除済み',pwBuy:'81県すべて解除',pwTry:'ムーラを見る',pwLocked:'ロック中',haveCode:'コードを持っています',codePh:'コードを入力',codeGo:'解除',codeOk:'解除しました！移動中…',codeErr:'このコードは無効です。',maps:'ルート',spots:'の絶景スポット',fullH:'次の目的地は世界',fullP:'Türkiyeを巡りました。次は世界中の場所があなたを待っています。',fullB:'世界のすべての場所'},
zh:{h1:'探索<br>Türkiye',tag:'81个省份的风景胜地。',trend:'热门',regions:'地区',search:'搜索省份…',tap:'打开',freeTap:'免费',lockedTap:'购买',ownTxt:'已解锁',pwBuy:'解锁全部81个',pwTry:'探索穆拉',pwLocked:'已锁定',haveCode:'我有代码',codePh:'输入代码',codeGo:'解锁',codeOk:'已解锁！跳转中…',codeErr:'此代码无效。',maps:'路线',spots:'个风景地点',fullH:'下一站：世界',fullP:'你已探索Türkiye。现在全世界都在等你。',fullB:'世界各地'},
ar:{h1:'اكتشف<br>Türkiye',tag:'أماكن خلابة في 81 محافظة.',trend:'الأكثر رواجاً',regions:'المناطق',search:'ابحث عن محافظة…',tap:'فتح',freeTap:'مجاني',lockedTap:'شراء',ownTxt:'مفتوح',pwBuy:'افتح كل الـ81',pwTry:'استكشف موغلا',pwLocked:'مقفل',haveCode:'لدي رمز',codePh:'أدخل الرمز',codeGo:'فتح',codeOk:'تم الفتح! جارٍ التحويل…',codeErr:'هذا الرمز غير صالح.',maps:'الاتجاهات',spots:'أماكن للاستكشاف',fullH:'المحطة التالية: العالم',fullP:'لقد استكشفت Türkiye. الآن ينتظرك العالم كله.',fullB:'كل أماكن العالم'},
hi:{h1:'खोजें<br>Türkiye',tag:'81 प्रांतों के दर्शनीय स्थल।',trend:'लोकप्रिय',regions:'क्षेत्र',search:'प्रांत खोजें…',tap:'खोलें',freeTap:'मुफ़्त',lockedTap:'खरीदें',ownTxt:'अनलॉक',pwBuy:'सभी 81 अनलॉक करें',pwTry:'मुग्ला देखें',pwLocked:'लॉक',haveCode:'मेरे पास कोड है',codePh:'अपना कोड डालें',codeGo:'अनलॉक',codeOk:'अनलॉक! रीडायरेक्ट हो रहा है…',codeErr:'यह कोड मान्य नहीं है।',maps:'दिशा',spots:'दर्शनीय स्थल',fullH:'अगला पड़ाव: दुनिया',fullP:'आपने Türkiye देखा। अब पूरी दुनिया इंतज़ार कर रही है।',fullB:'दुनिया के सभी स्थान'},
ko:{h1:'발견하세요<br>Türkiye',tag:'81개 주의 경치 좋은 명소.',trend:'인기',regions:'지역',search:'주 검색…',tap:'열기',freeTap:'무료',lockedTap:'구매',ownTxt:'잠금 해제',pwBuy:'81개 모두 잠금 해제',pwTry:'무을라 보기',pwLocked:'잠김',haveCode:'코드가 있어요',codePh:'코드 입력',codeGo:'잠금 해제',codeOk:'잠금 해제! 이동 중…',codeErr:'유효하지 않은 코드입니다.',maps:'길찾기',spots:'곳의 명소',fullH:'다음 목적지: 세계',fullP:'Türkiye를 둘러봤습니다. 이제 전 세계가 기다립니다.',fullB:'세계 모든 장소'},
nl:{h1:'Ontdek<br>Türkiye',tag:'Schilderachtige plekken in 81 provincies.',trend:'Populair',regions:'Regio’s',search:'Zoek een provincie…',tap:'Openen',freeTap:'Gratis',lockedTap:'Kopen',ownTxt:'Ontgrendeld',pwBuy:'Ontgrendel alle 81',pwTry:'Ontdek Muğla',pwLocked:'vergrendeld',haveCode:'Ik heb een code',codePh:'Voer je code in',codeGo:'Ontgrendel',codeOk:'Ontgrendeld! Doorsturen…',codeErr:'Deze code is ongeldig.',maps:'Route',spots:'mooie plekken',fullH:'Volgende halte: de wereld',fullP:'Je hebt Türkiye verkend. Nu wacht de hele wereld.',fullB:'Alle plekken wereldwijd'},
pl:{h1:'Odkryj<br>Türkiye',tag:'Malownicze miejsca w 81 prowincjach.',trend:'Popularne',regions:'Regiony',search:'Szukaj prowincji…',tap:'Otwórz',freeTap:'Za darmo',lockedTap:'Kup',ownTxt:'Odblokowane',pwBuy:'Odblokuj wszystkie 81',pwTry:'Odkryj Muğlę',pwLocked:'zablokowane',haveCode:'Mam kod',codePh:'Wpisz kod',codeGo:'Odblokuj',codeOk:'Odblokowano! Przekierowanie…',codeErr:'Ten kod jest nieprawidłowy.',maps:'Trasa',spots:'miejsc do odkrycia',fullH:'Następny przystanek: świat',fullP:'Poznałeś Türkiye. Teraz czeka cały świat.',fullB:'Wszystkie miejsca świata'},
sv:{h1:'Upptäck<br>Türkiye',tag:'Natursköna platser i 81 provinser.',trend:'Populärt',regions:'Regioner',search:'Sök provins…',tap:'Öppna',freeTap:'Gratis',lockedTap:'Köp',ownTxt:'Upplåst',pwBuy:'Lås upp alla 81',pwTry:'Utforska Muğla',pwLocked:'låst',haveCode:'Jag har en kod',codePh:'Ange din kod',codeGo:'Lås upp',codeOk:'Upplåst! Omdirigerar…',codeErr:'Koden är ogiltig.',maps:'Vägbeskrivning',spots:'sevärda platser',fullH:'Nästa stopp: världen',fullP:'Du har utforskat Türkiye. Nu väntar hela världen.',fullB:'Alla platser i världen'},
no:{h1:'Oppdag<br>Türkiye',tag:'Naturskjønne steder i 81 provinser.',trend:'Populært',regions:'Regioner',search:'Søk provins…',tap:'Åpne',freeTap:'Gratis',lockedTap:'Kjøp',ownTxt:'Låst opp',pwBuy:'Lås opp alle 81',pwTry:'Utforsk Muğla',pwLocked:'låst',haveCode:'Jeg har en kode',codePh:'Skriv inn koden',codeGo:'Lås opp',codeOk:'Låst opp! Omdirigerer…',codeErr:'Koden er ugyldig.',maps:'Veibeskrivelse',spots:'severdige steder',fullH:'Neste stopp: verden',fullP:'Du har utforsket Türkiye. Nå venter hele verden.',fullB:'Alle steder i verden'},
da:{h1:'Opdag<br>Türkiye',tag:'Naturskønne steder i 81 provinser.',trend:'Populært',regions:'Regioner',search:'Søg provins…',tap:'Åbn',freeTap:'Gratis',lockedTap:'Køb',ownTxt:'Låst op',pwBuy:'Lås alle 81 op',pwTry:'Udforsk Muğla',pwLocked:'låst',haveCode:'Jeg har en kode',codePh:'Indtast din kode',codeGo:'Lås op',codeOk:'Låst op! Omdirigerer…',codeErr:'Koden er ugyldig.',maps:'Rutevejledning',spots:'seværdige steder',fullH:'Næste stop: verden',fullP:'Du har udforsket Türkiye. Nu venter hele verden.',fullB:'Alle steder i verden'},
fi:{h1:'Löydä<br>Türkiye',tag:'Maisemakohteita 81 maakunnassa.',trend:'Suosittua',regions:'Alueet',search:'Hae maakuntaa…',tap:'Avaa',freeTap:'Ilmainen',lockedTap:'Osta',ownTxt:'Avattu',pwBuy:'Avaa kaikki 81',pwTry:'Tutustu Muğlaan',pwLocked:'lukittu',haveCode:'Minulla on koodi',codePh:'Syötä koodi',codeGo:'Avaa',codeOk:'Avattu! Ohjataan…',codeErr:'Koodi ei kelpaa.',maps:'Reittiohjeet',spots:'nähtävyyttä',fullH:'Seuraava pysäkki: maailma',fullP:'Olet tutkinut Türkiyen. Nyt koko maailma odottaa.',fullB:'Kaikki maailman paikat'},
cs:{h1:'Objevte<br>Türkiye',tag:'Malebná místa v 81 provinciích.',trend:'Populární',regions:'Regiony',search:'Hledat provincii…',tap:'Otevřít',freeTap:'Zdarma',lockedTap:'Koupit',ownTxt:'Odemčeno',pwBuy:'Odemknout všech 81',pwTry:'Prozkoumat Muğlu',pwLocked:'zamčeno',haveCode:'Mám kód',codePh:'Zadejte kód',codeGo:'Odemknout',codeOk:'Odemčeno! Přesměrování…',codeErr:'Tento kód je neplatný.',maps:'Trasa',spots:'míst k objevení',fullH:'Další zastávka: svět',fullP:'Prozkoumali jste Türkiye. Teď čeká celý svět.',fullB:'Všechna místa světa'},
el:{h1:'Ανακαλύψτε<br>Türkiye',tag:'Γραφικά μέρη σε 81 επαρχίες.',trend:'Δημοφιλή',regions:'Περιοχές',search:'Αναζήτηση επαρχίας…',tap:'Άνοιγμα',freeTap:'Δωρεάν',lockedTap:'Αγορά',ownTxt:'Ξεκλειδωμένο',pwBuy:'Ξεκλειδώστε και τις 81',pwTry:'Εξερευνήστε τη Μούγλα',pwLocked:'κλειδωμένο',haveCode:'Έχω κωδικό',codePh:'Εισάγετε τον κωδικό',codeGo:'Ξεκλείδωμα',codeOk:'Ξεκλειδώθηκε! Ανακατεύθυνση…',codeErr:'Ο κωδικός δεν είναι έγκυρος.',maps:'Οδηγίες',spots:'αξιοθέατα',fullH:'Επόμενη στάση: ο κόσμος',fullP:'Εξερευνήσατε την Türkiye. Τώρα σας περιμένει όλος ο κόσμος.',fullB:'Όλα τα μέρη του κόσμου'},
hu:{h1:'Fedezd fel<br>Türkiye',tag:'Festői helyek 81 tartományban.',trend:'Népszerű',regions:'Régiók',search:'Tartomány keresése…',tap:'Megnyitás',freeTap:'Ingyenes',lockedTap:'Vásárlás',ownTxt:'Feloldva',pwBuy:'Mind a 81 feloldása',pwTry:'Fedezd fel Muğlát',pwLocked:'zárolva',haveCode:'Van kódom',codePh:'Add meg a kódot',codeGo:'Feloldás',codeOk:'Feloldva! Átirányítás…',codeErr:'Ez a kód érvénytelen.',maps:'Útvonal',spots:'látnivaló',fullH:'Következő állomás: a világ',fullP:'Felfedezted Türkiyét. Most az egész világ vár.',fullB:'A világ összes helye'},
ro:{h1:'Descoperă<br>Türkiye',tag:'Locuri pitorești în 81 de provincii.',trend:'Populare',regions:'Regiuni',search:'Caută o provincie…',tap:'Deschide',freeTap:'Gratuit',lockedTap:'Cumpără',ownTxt:'Deblocat',pwBuy:'Deblochează toate cele 81',pwTry:'Explorează Muğla',pwLocked:'blocat',haveCode:'Am un cod',codePh:'Introdu codul',codeGo:'Deblochează',codeOk:'Deblocat! Redirecționare…',codeErr:'Acest cod nu este valid.',maps:'Indicații',spots:'locuri de explorat',fullH:'Următoarea oprire: lumea',fullP:'Ai explorat Türkiye. Acum te așteaptă întreaga lume.',fullB:'Toate locurile lumii'},
uk:{h1:'Відкрийте<br>Türkiye',tag:'Мальовничі місця у 81 провінції.',trend:'Популярне',regions:'Регіони',search:'Пошук провінції…',tap:'Відкрити',freeTap:'Безкоштовно',lockedTap:'Купити',ownTxt:'Відкрито',pwBuy:'Відкрити всі 81',pwTry:'Дослідити Муглу',pwLocked:'заблоковано',haveCode:'У мене є код',codePh:'Введіть код',codeGo:'Відкрити',codeOk:'Відкрито! Перенаправлення…',codeErr:'Код недійсний.',maps:'Маршрут',spots:'місць для відкриття',fullH:'Наступна зупинка: світ',fullP:'Ви дослідили Türkiye. Тепер на вас чекає весь світ.',fullB:'Усі місця світу'},
bg:{h1:'Открийте<br>Türkiye',tag:'Живописни места в 81 провинции.',trend:'Популярни',regions:'Региони',search:'Търсене на провинция…',tap:'Отвори',freeTap:'Безплатно',lockedTap:'Купи',ownTxt:'Отключено',pwBuy:'Отключи всички 81',pwTry:'Разгледай Мугла',pwLocked:'заключено',haveCode:'Имам код',codePh:'Въведете кода',codeGo:'Отключи',codeOk:'Отключено! Пренасочване…',codeErr:'Кодът е невалиден.',maps:'Упътване',spots:'места за разглеждане',fullH:'Следваща спирка: светът',fullP:'Разгледахте Türkiye. Сега ви очаква целият свят.',fullB:'Всички места по света'},
sr:{h1:'Otkrijte<br>Türkiye',tag:'Slikovita mesta u 81 provinciji.',trend:'Popularno',regions:'Regioni',search:'Pretraži provinciju…',tap:'Otvori',freeTap:'Besplatno',lockedTap:'Kupi',ownTxt:'Otključano',pwBuy:'Otključaj svih 81',pwTry:'Istraži Muglu',pwLocked:'zaključano',haveCode:'Imam kod',codePh:'Unesite kod',codeGo:'Otključaj',codeOk:'Otključano! Preusmeravanje…',codeErr:'Kod nije važeći.',maps:'Putanja',spots:'mesta za istraživanje',fullH:'Sledeća stanica: svet',fullP:'Istražili ste Türkiye. Sada vas čeka ceo svet.',fullB:'Sva mesta sveta'},
hr:{h1:'Otkrijte<br>Türkiye',tag:'Slikovita mjesta u 81 pokrajini.',trend:'Popularno',regions:'Regije',search:'Pretraži pokrajinu…',tap:'Otvori',freeTap:'Besplatno',lockedTap:'Kupi',ownTxt:'Otključano',pwBuy:'Otključaj svih 81',pwTry:'Istraži Muglu',pwLocked:'zaključano',haveCode:'Imam kod',codePh:'Unesite kod',codeGo:'Otključaj',codeOk:'Otključano! Preusmjeravanje…',codeErr:'Kôd nije valjan.',maps:'Upute',spots:'mjesta za istražiti',fullH:'Sljedeća stanica: svijet',fullP:'Istražili ste Türkiye. Sada vas čeka cijeli svijet.',fullB:'Sva mjesta svijeta'},
sk:{h1:'Objavte<br>Türkiye',tag:'Malebné miesta v 81 provinciách.',trend:'Populárne',regions:'Regióny',search:'Hľadať provinciu…',tap:'Otvoriť',freeTap:'Zadarmo',lockedTap:'Kúpiť',ownTxt:'Odomknuté',pwBuy:'Odomknúť všetkých 81',pwTry:'Preskúmať Muğlu',pwLocked:'zamknuté',haveCode:'Mám kód',codePh:'Zadajte kód',codeGo:'Odomknúť',codeOk:'Odomknuté! Presmerovanie…',codeErr:'Tento kód je neplatný.',maps:'Trasa',spots:'miest na objavenie',fullH:'Ďalšia zastávka: svet',fullP:'Preskúmali ste Türkiye. Teraz čaká celý svet.',fullB:'Všetky miesta sveta'},
sl:{h1:'Odkrijte<br>Türkiye',tag:'Slikovita mesta v 81 pokrajinah.',trend:'Priljubljeno',regions:'Regije',search:'Iskanje pokrajine…',tap:'Odpri',freeTap:'Brezplačno',lockedTap:'Kupi',ownTxt:'Odklenjeno',pwBuy:'Odkleni vseh 81',pwTry:'Razišči Muğlo',pwLocked:'zaklenjeno',haveCode:'Imam kodo',codePh:'Vnesite kodo',codeGo:'Odkleni',codeOk:'Odklenjeno! Preusmerjanje…',codeErr:'Koda ni veljavna.',maps:'Navodila',spots:'znamenitosti',fullH:'Naslednja postaja: svet',fullP:'Raziskali ste Türkiye. Zdaj vas čaka ves svet.',fullB:'Vsa mesta sveta'},
lt:{h1:'Atraskite<br>Türkiye',tag:'Vaizdingos vietos 81 provincijoje.',trend:'Populiaru',regions:'Regionai',search:'Ieškoti provincijos…',tap:'Atidaryti',freeTap:'Nemokama',lockedTap:'Pirkti',ownTxt:'Atrakinta',pwBuy:'Atrakinti visas 81',pwTry:'Tyrinėti Muglą',pwLocked:'užrakinta',haveCode:'Turiu kodą',codePh:'Įveskite kodą',codeGo:'Atrakinti',codeOk:'Atrakinta! Nukreipiama…',codeErr:'Šis kodas negalioja.',maps:'Maršrutas',spots:'vietų tyrinėti',fullH:'Kita stotelė: pasaulis',fullP:'Ištyrinėjote Türkiye. Dabar laukia visas pasaulis.',fullB:'Visos pasaulio vietos'},
th:{h1:'ค้นพบ<br>Türkiye',tag:'สถานที่สวยงามใน 81 จังหวัด',trend:'ยอดนิยม',regions:'ภูมิภาค',search:'ค้นหาจังหวัด…',tap:'เปิด',freeTap:'ฟรี',lockedTap:'ซื้อ',ownTxt:'ปลดล็อกแล้ว',pwBuy:'ปลดล็อกทั้ง 81',pwTry:'สำรวจมูกลา',pwLocked:'ล็อก',haveCode:'ฉันมีรหัส',codePh:'ใส่รหัสของคุณ',codeGo:'ปลดล็อก',codeOk:'ปลดล็อกแล้ว! กำลังเปลี่ยนเส้นทาง…',codeErr:'รหัสนี้ไม่ถูกต้อง',maps:'เส้นทาง',spots:'สถานที่น่าสำรวจ',fullH:'จุดหมายต่อไป: โลก',fullP:'คุณได้สำรวจ Türkiye แล้ว ตอนนี้ทั้งโลกกำลังรอคุณ',fullB:'สถานที่ทั่วโลก'},
vi:{h1:'Khám phá<br>Türkiye',tag:'Những địa điểm đẹp ở 81 tỉnh.',trend:'Thịnh hành',regions:'Khu vực',search:'Tìm tỉnh…',tap:'Mở',freeTap:'Miễn phí',lockedTap:'Mua',ownTxt:'Đã mở khóa',pwBuy:'Mở khóa cả 81',pwTry:'Khám phá Muğla',pwLocked:'đã khóa',haveCode:'Tôi có mã',codePh:'Nhập mã của bạn',codeGo:'Mở khóa',codeOk:'Đã mở khóa! Đang chuyển hướng…',codeErr:'Mã không hợp lệ.',maps:'Chỉ đường',spots:'địa điểm để khám phá',fullH:'Điểm đến tiếp theo: thế giới',fullP:'Bạn đã khám phá Türkiye. Giờ cả thế giới đang chờ.',fullB:'Mọi địa điểm thế giới'},
id:{h1:'Jelajahi<br>Türkiye',tag:'Tempat indah di 81 provinsi.',trend:'Tren',regions:'Wilayah',search:'Cari provinsi…',tap:'Buka',freeTap:'Gratis',lockedTap:'Beli',ownTxt:'Terbuka',pwBuy:'Buka semua 81',pwTry:'Jelajahi Muğla',pwLocked:'terkunci',haveCode:'Saya punya kode',codePh:'Masukkan kode',codeGo:'Buka',codeOk:'Terbuka! Mengalihkan…',codeErr:'Kode tidak valid.',maps:'Rute',spots:'tempat untuk dijelajahi',fullH:'Perhentian berikutnya: dunia',fullP:'Anda telah menjelajahi Türkiye. Kini seluruh dunia menanti.',fullB:'Semua tempat di dunia'},
ms:{h1:'Terokai<br>Türkiye',tag:'Tempat indah di 81 wilayah.',trend:'Sohor kini',regions:'Wilayah',search:'Cari wilayah…',tap:'Buka',freeTap:'Percuma',lockedTap:'Beli',ownTxt:'Dibuka',pwBuy:'Buka semua 81',pwTry:'Terokai Muğla',pwLocked:'dikunci',haveCode:'Saya ada kod',codePh:'Masukkan kod',codeGo:'Buka',codeOk:'Dibuka! Mengalih…',codeErr:'Kod tidak sah.',maps:'Arah',spots:'tempat untuk diterokai',fullH:'Hentian seterusnya: dunia',fullP:'Anda telah menerokai Türkiye. Kini seluruh dunia menanti.',fullB:'Semua tempat di dunia'},
fa:{h1:'کشف کنید<br>Türkiye',tag:'مکان‌های دیدنی در ۸۱ استان.',trend:'پرطرفدار',regions:'مناطق',search:'جستجوی استان…',tap:'باز کردن',freeTap:'رایگان',lockedTap:'خرید',ownTxt:'باز شده',pwBuy:'باز کردن هر ۸۱',pwTry:'کاوش موغلا',pwLocked:'قفل',haveCode:'کد دارم',codePh:'کد خود را وارد کنید',codeGo:'باز کردن',codeOk:'باز شد! در حال انتقال…',codeErr:'این کد معتبر نیست.',maps:'مسیر',spots:'مکان دیدنی',fullH:'مقصد بعدی: جهان',fullP:'شما Türkiye را کاوش کردید. حالا تمام جهان منتظر شماست.',fullB:'همه مکان‌های جهان'},
he:{h1:'גלו את<br>Türkiye',tag:'מקומות נופיים ב-81 מחוזות.',trend:'מובילים',regions:'אזורים',search:'חיפוש מחוז…',tap:'פתיחה',freeTap:'חינם',lockedTap:'קנייה',ownTxt:'נפתח',pwBuy:'פתחו את כל ה-81',pwTry:'גלו את מוגלה',pwLocked:'נעול',haveCode:'יש לי קוד',codePh:'הזינו את הקוד',codeGo:'פתיחה',codeOk:'נפתח! מעביר…',codeErr:'הקוד אינו תקף.',maps:'הוראות הגעה',spots:'מקומות לגלות',fullH:'התחנה הבאה: העולם',fullP:'חקרתם את Türkiye. עכשיו כל העולם מחכה.',fullB:'כל המקומות בעולם'},
az:{h1:'Kəşf edin<br>Türkiye',tag:'81 vilayətdə mənzərəli yerlər.',trend:'Populyar',regions:'Bölgələr',search:'Vilayət axtar…',tap:'Aç',freeTap:'Pulsuz',lockedTap:'Al',ownTxt:'Açıldı',pwBuy:'Hamısını aç (81)',pwTry:'Muğlanı kəşf et',pwLocked:'kilidli',haveCode:'Kodum var',codePh:'Kodu daxil edin',codeGo:'Aç',codeOk:'Açıldı! Yönləndirilir…',codeErr:'Bu kod yanlışdır.',maps:'Marşrut',spots:'mənzərəli yer',fullH:'Növbəti dayanacaq: dünya',fullP:'Türkiyəni kəşf etdiniz. İndi bütün dünya sizi gözləyir.',fullB:'Dünyanın bütün yerləri'},
ka:{h1:'აღმოაჩინე<br>Türkiye',tag:'მშვენიერი ადგილები 81 პროვინციაში.',trend:'პოპულარული',regions:'რეგიონები',search:'პროვინციის ძებნა…',tap:'გახსნა',freeTap:'უფასო',lockedTap:'ყიდვა',ownTxt:'გახსნილი',pwBuy:'გახსენი ყველა 81',pwTry:'აღმოაჩინე მუღლა',pwLocked:'ჩაკეტილი',haveCode:'მაქვს კოდი',codePh:'შეიყვანეთ კოდი',codeGo:'გახსნა',codeOk:'გახსნილია! გადამისამართება…',codeErr:'კოდი არასწორია.',maps:'მარშრუტი',spots:'სანახავი ადგილი',fullH:'შემდეგი გაჩერება: მსოფლიო',fullP:'თქვენ დაათვალიერეთ Türkiye. ახლა მთელი მსოფლიო გელით.',fullB:'მსოფლიოს ყველა ადგილი'},
bn:{h1:'আবিষ্কার করুন<br>Türkiye',tag:'৮১টি প্রদেশের মনোরম স্থান।',trend:'জনপ্রিয়',regions:'অঞ্চল',search:'প্রদেশ খুঁজুন…',tap:'খুলুন',freeTap:'বিনামূল্যে',lockedTap:'কিনুন',ownTxt:'আনলক',pwBuy:'সব ৮১টি আনলক করুন',pwTry:'মুগলা দেখুন',pwLocked:'লক',haveCode:'আমার কোড আছে',codePh:'আপনার কোড দিন',codeGo:'আনলক',codeOk:'আনলক! রিডাইরেক্ট হচ্ছে…',codeErr:'এই কোডটি বৈধ নয়।',maps:'দিকনির্দেশ',spots:'দর্শনীয় স্থান',fullH:'পরবর্তী গন্তব্য: বিশ্ব',fullP:'আপনি Türkiye ঘুরেছেন। এখন সারা বিশ্ব অপেক্ষা করছে।',fullB:'বিশ্বের সব স্থান'},
ur:{h1:'دریافت کریں<br>Türkiye',tag:'۸۱ صوبوں میں خوبصورت مقامات۔',trend:'مقبول',regions:'علاقے',search:'صوبہ تلاش کریں…',tap:'کھولیں',freeTap:'مفت',lockedTap:'خریدیں',ownTxt:'انلاک',pwBuy:'تمام ۸۱ انلاک کریں',pwTry:'موغلا دیکھیں',pwLocked:'مقفل',haveCode:'میرے پاس کوڈ ہے',codePh:'اپنا کوڈ درج کریں',codeGo:'انلاک',codeOk:'انلاک! ری ڈائریکٹ ہو رہا ہے…',codeErr:'یہ کوڈ درست نہیں ہے۔',maps:'راستہ',spots:'دیکھنے کی جگہیں',fullH:'اگلا پڑاؤ: دنیا',fullP:'آپ نے Türkiye دیکھا۔ اب پوری دنیا منتظر ہے۔',fullB:'دنیا کے تمام مقامات'}
};
const RTL={ar:1,he:1,fa:1,ur:1};
function pick(){
  const b=(navigator.language||navigator.userLanguage||'en').toLowerCase();
  if(b.startsWith('tr'))return 'tr';
  const two=b.slice(0,2);
  return D[two]?two:'en';
}
const lang=pick();
const t=Object.assign({},D.en,D[lang]||{});
t.names=REG[lang]||REG.en;
/* not: dir=rtl AYARLAMA — LTR tasarımı bozar; RTL metin bidi ile zaten doğru görünür */
try{document.documentElement.lang=lang;}catch(e){}
return {lang:lang,t:t,rtl:!!RTL[lang]};
})();
